# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # https://circleci.com/developer/images/image/cimg/node
      # use "cimg/node:lts-browsers" if you need a browser
      - image: cimg/node:lts

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ls -la && pwd
      - run: git --version
      - run: npm install
      - run: npm run build:lib
      - run: ls -la && pwd

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
                root: .
                paths:
                  - dist
      # run tests!
      #- run: npm test




